// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAuthSamlProvidersProviderIDReader is a Reader for the DeleteAuthSamlProvidersProviderID structure.
type DeleteAuthSamlProvidersProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAuthSamlProvidersProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAuthSamlProvidersProviderIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAuthSamlProvidersProviderIDNoContent creates a DeleteAuthSamlProvidersProviderIDNoContent with default headers values
func NewDeleteAuthSamlProvidersProviderIDNoContent() *DeleteAuthSamlProvidersProviderIDNoContent {
	return &DeleteAuthSamlProvidersProviderIDNoContent{}
}

/*DeleteAuthSamlProvidersProviderIDNoContent handles this case with default header values.

Success.
*/
type DeleteAuthSamlProvidersProviderIDNoContent struct {
}

func (o *DeleteAuthSamlProvidersProviderIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /auth/saml/providers/{provider-id}][%d] deleteAuthSamlProvidersProviderIdNoContent ", 204)
}

func (o *DeleteAuthSamlProvidersProviderIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
