// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAuthSamlProvidersReader is a Reader for the GetAuthSamlProviders structure.
type GetAuthSamlProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthSamlProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthSamlProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthSamlProvidersOK creates a GetAuthSamlProvidersOK with default headers values
func NewGetAuthSamlProvidersOK() *GetAuthSamlProvidersOK {
	return &GetAuthSamlProvidersOK{}
}

/*GetAuthSamlProvidersOK handles this case with default header values.

Success.
*/
type GetAuthSamlProvidersOK struct {
}

func (o *GetAuthSamlProvidersOK) Error() string {
	return fmt.Sprintf("[GET /auth/saml/providers][%d] getAuthSamlProvidersOK ", 200)
}

func (o *GetAuthSamlProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
