// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchAuthSamlProvidersProviderIDReader is a Reader for the PatchAuthSamlProvidersProviderID structure.
type PatchAuthSamlProvidersProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAuthSamlProvidersProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPatchAuthSamlProvidersProviderIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPatchAuthSamlProvidersProviderIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchAuthSamlProvidersProviderIDNoContent creates a PatchAuthSamlProvidersProviderIDNoContent with default headers values
func NewPatchAuthSamlProvidersProviderIDNoContent() *PatchAuthSamlProvidersProviderIDNoContent {
	return &PatchAuthSamlProvidersProviderIDNoContent{}
}

/*PatchAuthSamlProvidersProviderIDNoContent handles this case with default header values.

Update applied.
*/
type PatchAuthSamlProvidersProviderIDNoContent struct {
}

func (o *PatchAuthSamlProvidersProviderIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /auth/saml/providers/{provider-id}][%d] patchAuthSamlProvidersProviderIdNoContent ", 204)
}

func (o *PatchAuthSamlProvidersProviderIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchAuthSamlProvidersProviderIDBadRequest creates a PatchAuthSamlProvidersProviderIDBadRequest with default headers values
func NewPatchAuthSamlProvidersProviderIDBadRequest() *PatchAuthSamlProvidersProviderIDBadRequest {
	return &PatchAuthSamlProvidersProviderIDBadRequest{}
}

/*PatchAuthSamlProvidersProviderIDBadRequest handles this case with default header values.

Various errors (e.g. provider not yet configured).
*/
type PatchAuthSamlProvidersProviderIDBadRequest struct {
}

func (o *PatchAuthSamlProvidersProviderIDBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /auth/saml/providers/{provider-id}][%d] patchAuthSamlProvidersProviderIdBadRequest ", 400)
}

func (o *PatchAuthSamlProvidersProviderIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
