// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAuthSamlProvidersProviderIDAcsCallbackReader is a Reader for the PostAuthSamlProvidersProviderIDAcsCallback structure.
type PostAuthSamlProvidersProviderIDAcsCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthSamlProvidersProviderIDAcsCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 302:
		result := NewPostAuthSamlProvidersProviderIDAcsCallbackFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostAuthSamlProvidersProviderIDAcsCallbackUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAuthSamlProvidersProviderIDAcsCallbackFound creates a PostAuthSamlProvidersProviderIDAcsCallbackFound with default headers values
func NewPostAuthSamlProvidersProviderIDAcsCallbackFound() *PostAuthSamlProvidersProviderIDAcsCallbackFound {
	return &PostAuthSamlProvidersProviderIDAcsCallbackFound{}
}

/*PostAuthSamlProvidersProviderIDAcsCallbackFound handles this case with default header values.

SAML authentication flow successful.
*/
type PostAuthSamlProvidersProviderIDAcsCallbackFound struct {
}

func (o *PostAuthSamlProvidersProviderIDAcsCallbackFound) Error() string {
	return fmt.Sprintf("[POST /auth/saml/providers/{provider-id}/acs-callback][%d] postAuthSamlProvidersProviderIdAcsCallbackFound ", 302)
}

func (o *PostAuthSamlProvidersProviderIDAcsCallbackFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAuthSamlProvidersProviderIDAcsCallbackUnauthorized creates a PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized with default headers values
func NewPostAuthSamlProvidersProviderIDAcsCallbackUnauthorized() *PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized {
	return &PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized{}
}

/*PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized handles this case with default header values.

Problem in authentication flow.
*/
type PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized struct {
}

func (o *PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized) Error() string {
	return fmt.Sprintf("[POST /auth/saml/providers/{provider-id}/acs-callback][%d] postAuthSamlProvidersProviderIdAcsCallbackUnauthorized ", 401)
}

func (o *PostAuthSamlProvidersProviderIDAcsCallbackUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
