// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// NewPutAuthSamlProvidersProviderIDParams creates a new PutAuthSamlProvidersProviderIDParams object
// with the default values initialized.
func NewPutAuthSamlProvidersProviderIDParams() *PutAuthSamlProvidersProviderIDParams {
	var ()
	return &PutAuthSamlProvidersProviderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAuthSamlProvidersProviderIDParamsWithTimeout creates a new PutAuthSamlProvidersProviderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAuthSamlProvidersProviderIDParamsWithTimeout(timeout time.Duration) *PutAuthSamlProvidersProviderIDParams {
	var ()
	return &PutAuthSamlProvidersProviderIDParams{

		timeout: timeout,
	}
}

// NewPutAuthSamlProvidersProviderIDParamsWithContext creates a new PutAuthSamlProvidersProviderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAuthSamlProvidersProviderIDParamsWithContext(ctx context.Context) *PutAuthSamlProvidersProviderIDParams {
	var ()
	return &PutAuthSamlProvidersProviderIDParams{

		Context: ctx,
	}
}

// NewPutAuthSamlProvidersProviderIDParamsWithHTTPClient creates a new PutAuthSamlProvidersProviderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAuthSamlProvidersProviderIDParamsWithHTTPClient(client *http.Client) *PutAuthSamlProvidersProviderIDParams {
	var ()
	return &PutAuthSamlProvidersProviderIDParams{
		HTTPClient: client,
	}
}

/*PutAuthSamlProvidersProviderIDParams contains all the parameters to send to the API endpoint
for the put auth saml providers provider ID operation typically these are written to a http.Request
*/
type PutAuthSamlProvidersProviderIDParams struct {

	/*ProviderConfigObject
	  Provider config JSON object

	*/
	ProviderConfigObject *models.SAMLProviderConfig
	/*ProviderID
	  The ID of the provider to create.

	*/
	ProviderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) WithTimeout(timeout time.Duration) *PutAuthSamlProvidersProviderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) WithContext(ctx context.Context) *PutAuthSamlProvidersProviderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) WithHTTPClient(client *http.Client) *PutAuthSamlProvidersProviderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderConfigObject adds the providerConfigObject to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) WithProviderConfigObject(providerConfigObject *models.SAMLProviderConfig) *PutAuthSamlProvidersProviderIDParams {
	o.SetProviderConfigObject(providerConfigObject)
	return o
}

// SetProviderConfigObject adds the providerConfigObject to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) SetProviderConfigObject(providerConfigObject *models.SAMLProviderConfig) {
	o.ProviderConfigObject = providerConfigObject
}

// WithProviderID adds the providerID to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) WithProviderID(providerID string) *PutAuthSamlProvidersProviderIDParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the put auth saml providers provider ID params
func (o *PutAuthSamlProvidersProviderIDParams) SetProviderID(providerID string) {
	o.ProviderID = providerID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAuthSamlProvidersProviderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProviderConfigObject != nil {
		if err := r.SetBodyParam(o.ProviderConfigObject); err != nil {
			return err
		}
	}

	// path param provider-id
	if err := r.SetPathParam("provider-id", o.ProviderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
