// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAuthSamlProvidersProviderIDReader is a Reader for the PutAuthSamlProvidersProviderID structure.
type PutAuthSamlProvidersProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAuthSamlProvidersProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutAuthSamlProvidersProviderIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPutAuthSamlProvidersProviderIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAuthSamlProvidersProviderIDCreated creates a PutAuthSamlProvidersProviderIDCreated with default headers values
func NewPutAuthSamlProvidersProviderIDCreated() *PutAuthSamlProvidersProviderIDCreated {
	return &PutAuthSamlProvidersProviderIDCreated{}
}

/*PutAuthSamlProvidersProviderIDCreated handles this case with default header values.

Provider created.
*/
type PutAuthSamlProvidersProviderIDCreated struct {
}

func (o *PutAuthSamlProvidersProviderIDCreated) Error() string {
	return fmt.Sprintf("[PUT /auth/saml/providers/{provider-id}][%d] putAuthSamlProvidersProviderIdCreated ", 201)
}

func (o *PutAuthSamlProvidersProviderIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAuthSamlProvidersProviderIDConflict creates a PutAuthSamlProvidersProviderIDConflict with default headers values
func NewPutAuthSamlProvidersProviderIDConflict() *PutAuthSamlProvidersProviderIDConflict {
	return &PutAuthSamlProvidersProviderIDConflict{}
}

/*PutAuthSamlProvidersProviderIDConflict handles this case with default header values.

Provider already exists.
*/
type PutAuthSamlProvidersProviderIDConflict struct {
}

func (o *PutAuthSamlProvidersProviderIDConflict) Error() string {
	return fmt.Sprintf("[PUT /auth/saml/providers/{provider-id}][%d] putAuthSamlProvidersProviderIdConflict ", 409)
}

func (o *PutAuthSamlProvidersProviderIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
