// Code generated by go-swagger; DO NOT EDIT.

package ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// PostLdapConfigTestReader is a Reader for the PostLdapConfigTest structure.
type PostLdapConfigTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLdapConfigTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostLdapConfigTestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 502:
		result := NewPostLdapConfigTestBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLdapConfigTestOK creates a PostLdapConfigTestOK with default headers values
func NewPostLdapConfigTestOK() *PostLdapConfigTestOK {
	return &PostLdapConfigTestOK{}
}

/*PostLdapConfigTestOK handles this case with default header values.

Directory back-end was reached and all feature tests passed.
*/
type PostLdapConfigTestOK struct {
	Payload *models.LDAPTestResultObject
}

func (o *PostLdapConfigTestOK) Error() string {
	return fmt.Sprintf("[POST /ldap/config/test][%d] postLdapConfigTestOK  %+v", 200, o.Payload)
}

func (o *PostLdapConfigTestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LDAPTestResultObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostLdapConfigTestBadGateway creates a PostLdapConfigTestBadGateway with default headers values
func NewPostLdapConfigTestBadGateway() *PostLdapConfigTestBadGateway {
	return &PostLdapConfigTestBadGateway{}
}

/*PostLdapConfigTestBadGateway handles this case with default header values.

Either there was a connection error or one of the feature tests failed. To distinguish this response from a proxy-generated 502, a JSON object is included in the response. It contains a message in its `description` property, describing the problem in more detail.
*/
type PostLdapConfigTestBadGateway struct {
	Payload *models.LDAPTestResultObject
}

func (o *PostLdapConfigTestBadGateway) Error() string {
	return fmt.Sprintf("[POST /ldap/config/test][%d] postLdapConfigTestBadGateway  %+v", 502, o.Payload)
}

func (o *PostLdapConfigTestBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LDAPTestResultObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
