// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteGroupsGidUsersUIDReader is a Reader for the DeleteGroupsGidUsersUID structure.
type DeleteGroupsGidUsersUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGroupsGidUsersUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteGroupsGidUsersUIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGroupsGidUsersUIDNoContent creates a DeleteGroupsGidUsersUIDNoContent with default headers values
func NewDeleteGroupsGidUsersUIDNoContent() *DeleteGroupsGidUsersUIDNoContent {
	return &DeleteGroupsGidUsersUIDNoContent{}
}

/*DeleteGroupsGidUsersUIDNoContent handles this case with default header values.

Success.
*/
type DeleteGroupsGidUsersUIDNoContent struct {
}

func (o *DeleteGroupsGidUsersUIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /groups/{gid}/users/{uid}][%d] deleteGroupsGidUsersUidNoContent ", 204)
}

func (o *DeleteGroupsGidUsersUIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
