// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteGroupsGidReader is a Reader for the DeleteGroupsGid structure.
type DeleteGroupsGidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGroupsGidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteGroupsGidNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGroupsGidNoContent creates a DeleteGroupsGidNoContent with default headers values
func NewDeleteGroupsGidNoContent() *DeleteGroupsGidNoContent {
	return &DeleteGroupsGidNoContent{}
}

/*DeleteGroupsGidNoContent handles this case with default header values.

Success
*/
type DeleteGroupsGidNoContent struct {
}

func (o *DeleteGroupsGidNoContent) Error() string {
	return fmt.Sprintf("[DELETE /groups/{gid}][%d] deleteGroupsGidNoContent ", 204)
}

func (o *DeleteGroupsGidNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
