// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteGroupsGidParams creates a new DeleteGroupsGidParams object
// with the default values initialized.
func NewDeleteGroupsGidParams() *DeleteGroupsGidParams {
	var ()
	return &DeleteGroupsGidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGroupsGidParamsWithTimeout creates a new DeleteGroupsGidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteGroupsGidParamsWithTimeout(timeout time.Duration) *DeleteGroupsGidParams {
	var ()
	return &DeleteGroupsGidParams{

		timeout: timeout,
	}
}

// NewDeleteGroupsGidParamsWithContext creates a new DeleteGroupsGidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteGroupsGidParamsWithContext(ctx context.Context) *DeleteGroupsGidParams {
	var ()
	return &DeleteGroupsGidParams{

		Context: ctx,
	}
}

// NewDeleteGroupsGidParamsWithHTTPClient creates a new DeleteGroupsGidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteGroupsGidParamsWithHTTPClient(client *http.Client) *DeleteGroupsGidParams {
	var ()
	return &DeleteGroupsGidParams{
		HTTPClient: client,
	}
}

/*DeleteGroupsGidParams contains all the parameters to send to the API endpoint
for the delete groups gid operation typically these are written to a http.Request
*/
type DeleteGroupsGidParams struct {

	/*Gid
	  The ID of the group to delete.

	*/
	Gid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete groups gid params
func (o *DeleteGroupsGidParams) WithTimeout(timeout time.Duration) *DeleteGroupsGidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete groups gid params
func (o *DeleteGroupsGidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete groups gid params
func (o *DeleteGroupsGidParams) WithContext(ctx context.Context) *DeleteGroupsGidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete groups gid params
func (o *DeleteGroupsGidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete groups gid params
func (o *DeleteGroupsGidParams) WithHTTPClient(client *http.Client) *DeleteGroupsGidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete groups gid params
func (o *DeleteGroupsGidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGid adds the gid to the delete groups gid params
func (o *DeleteGroupsGidParams) WithGid(gid string) *DeleteGroupsGidParams {
	o.SetGid(gid)
	return o
}

// SetGid adds the gid to the delete groups gid params
func (o *DeleteGroupsGidParams) SetGid(gid string) {
	o.Gid = gid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGroupsGidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gid
	if err := r.SetPathParam("gid", o.Gid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
