// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// GetGroupsGidReader is a Reader for the GetGroupsGid structure.
type GetGroupsGidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupsGidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGroupsGidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupsGidOK creates a GetGroupsGidOK with default headers values
func NewGetGroupsGidOK() *GetGroupsGidOK {
	return &GetGroupsGidOK{}
}

/*GetGroupsGidOK handles this case with default header values.

Success.
*/
type GetGroupsGidOK struct {
	Payload *models.Group
}

func (o *GetGroupsGidOK) Error() string {
	return fmt.Sprintf("[GET /groups/{gid}][%d] getGroupsGidOK  %+v", 200, o.Payload)
}

func (o *GetGroupsGidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
