// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// GetGroupsGidUsersReader is a Reader for the GetGroupsGidUsers structure.
type GetGroupsGidUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupsGidUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGroupsGidUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupsGidUsersOK creates a GetGroupsGidUsersOK with default headers values
func NewGetGroupsGidUsersOK() *GetGroupsGidUsersOK {
	return &GetGroupsGidUsersOK{}
}

/*GetGroupsGidUsersOK handles this case with default header values.

Success.
*/
type GetGroupsGidUsersOK struct {
	Payload *models.GroupUsers
}

func (o *GetGroupsGidUsersOK) Error() string {
	return fmt.Sprintf("[GET /groups/{gid}/users][%d] getGroupsGidUsersOK  %+v", 200, o.Payload)
}

func (o *GetGroupsGidUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupUsers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
