// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutGroupsGidUsersUIDParams creates a new PutGroupsGidUsersUIDParams object
// with the default values initialized.
func NewPutGroupsGidUsersUIDParams() *PutGroupsGidUsersUIDParams {
	var ()
	return &PutGroupsGidUsersUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutGroupsGidUsersUIDParamsWithTimeout creates a new PutGroupsGidUsersUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutGroupsGidUsersUIDParamsWithTimeout(timeout time.Duration) *PutGroupsGidUsersUIDParams {
	var ()
	return &PutGroupsGidUsersUIDParams{

		timeout: timeout,
	}
}

// NewPutGroupsGidUsersUIDParamsWithContext creates a new PutGroupsGidUsersUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutGroupsGidUsersUIDParamsWithContext(ctx context.Context) *PutGroupsGidUsersUIDParams {
	var ()
	return &PutGroupsGidUsersUIDParams{

		Context: ctx,
	}
}

// NewPutGroupsGidUsersUIDParamsWithHTTPClient creates a new PutGroupsGidUsersUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutGroupsGidUsersUIDParamsWithHTTPClient(client *http.Client) *PutGroupsGidUsersUIDParams {
	var ()
	return &PutGroupsGidUsersUIDParams{
		HTTPClient: client,
	}
}

/*PutGroupsGidUsersUIDParams contains all the parameters to send to the API endpoint
for the put groups gid users UID operation typically these are written to a http.Request
*/
type PutGroupsGidUsersUIDParams struct {

	/*Gid
	  The ID of the group to add the user account to.

	*/
	Gid string
	/*UID
	  The ID of the account to add.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) WithTimeout(timeout time.Duration) *PutGroupsGidUsersUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) WithContext(ctx context.Context) *PutGroupsGidUsersUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) WithHTTPClient(client *http.Client) *PutGroupsGidUsersUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGid adds the gid to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) WithGid(gid string) *PutGroupsGidUsersUIDParams {
	o.SetGid(gid)
	return o
}

// SetGid adds the gid to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) SetGid(gid string) {
	o.Gid = gid
}

// WithUID adds the uid to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) WithUID(uid string) *PutGroupsGidUsersUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the put groups gid users UID params
func (o *PutGroupsGidUsersUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *PutGroupsGidUsersUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gid
	if err := r.SetPathParam("gid", o.Gid); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
