// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PackageDeleteRepoRequest package delete repo request
// swagger:model packageDeleteRepoRequest
type PackageDeleteRepoRequest struct {

	// name
	Name string `json:"name,omitempty"`

	// uri
	// Format: uri
	URI URL `json:"uri,omitempty"`
}

// Validate validates this package delete repo request
func (m *PackageDeleteRepoRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURI(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PackageDeleteRepoRequest) validateURI(formats strfmt.Registry) error {

	if swag.IsZero(m.URI) { // not required
		return nil
	}

	if err := m.URI.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("uri")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PackageDeleteRepoRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackageDeleteRepoRequest) UnmarshalBinary(b []byte) error {
	var res PackageDeleteRepoRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
