// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceUpdateResponse service update response
// swagger:model serviceUpdateResponse
type ServiceUpdateResponse struct {

	// marathon deployment Id
	// Required: true
	MarathonDeploymentID *string `json:"marathonDeploymentId"`

	// package
	// Required: true
	Package *V50PackageDefinition `json:"package"`

	// The result of merging the default package options with the user supplied options
	// Required: true
	ResolvedOptions interface{} `json:"resolvedOptions"`
}

// Validate validates this service update response
func (m *ServiceUpdateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMarathonDeploymentID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePackage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResolvedOptions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceUpdateResponse) validateMarathonDeploymentID(formats strfmt.Registry) error {

	if err := validate.Required("marathonDeploymentId", "body", m.MarathonDeploymentID); err != nil {
		return err
	}

	return nil
}

func (m *ServiceUpdateResponse) validatePackage(formats strfmt.Registry) error {

	if err := validate.Required("package", "body", m.Package); err != nil {
		return err
	}

	if m.Package != nil {
		if err := m.Package.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("package")
			}
			return err
		}
	}

	return nil
}

func (m *ServiceUpdateResponse) validateResolvedOptions(formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceUpdateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceUpdateResponse) UnmarshalBinary(b []byte) error {
	var res ServiceUpdateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
