sudo: false

language: go

go:
  - "1.11.x"
  - "1.12.x"

go_import_path: github.com/dcos/client-go

env:
 - GO111MODULE=on

before_install:
 - env GO111MODULE=off go get -u golang.org/x/lint/golint

script:
  - make validate
