sudo: false
language: go
go:
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
matrix:
  fast_finish: true
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
