/*
 *  DC/OS Secrets API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package secrets

type Secret struct {
	Value string `json:"value,omitempty"`
}
