// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAclsRidUsersUIDReader is a Reader for the DeleteAclsRidUsersUID structure.
type DeleteAclsRidUsersUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAclsRidUsersUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAclsRidUsersUIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAclsRidUsersUIDNoContent creates a DeleteAclsRidUsersUIDNoContent with default headers values
func NewDeleteAclsRidUsersUIDNoContent() *DeleteAclsRidUsersUIDNoContent {
	return &DeleteAclsRidUsersUIDNoContent{}
}

/*DeleteAclsRidUsersUIDNoContent handles this case with default header values.

Success.
*/
type DeleteAclsRidUsersUIDNoContent struct {
}

func (o *DeleteAclsRidUsersUIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /acls/{rid}/users/{uid}][%d] deleteAclsRidUsersUidNoContent ", 204)
}

func (o *DeleteAclsRidUsersUIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
