// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAclsRidUsersUIDActionParams creates a new DeleteAclsRidUsersUIDActionParams object
// with the default values initialized.
func NewDeleteAclsRidUsersUIDActionParams() *DeleteAclsRidUsersUIDActionParams {
	var ()
	return &DeleteAclsRidUsersUIDActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAclsRidUsersUIDActionParamsWithTimeout creates a new DeleteAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAclsRidUsersUIDActionParamsWithTimeout(timeout time.Duration) *DeleteAclsRidUsersUIDActionParams {
	var ()
	return &DeleteAclsRidUsersUIDActionParams{

		timeout: timeout,
	}
}

// NewDeleteAclsRidUsersUIDActionParamsWithContext creates a new DeleteAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAclsRidUsersUIDActionParamsWithContext(ctx context.Context) *DeleteAclsRidUsersUIDActionParams {
	var ()
	return &DeleteAclsRidUsersUIDActionParams{

		Context: ctx,
	}
}

// NewDeleteAclsRidUsersUIDActionParamsWithHTTPClient creates a new DeleteAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAclsRidUsersUIDActionParamsWithHTTPClient(client *http.Client) *DeleteAclsRidUsersUIDActionParams {
	var ()
	return &DeleteAclsRidUsersUIDActionParams{
		HTTPClient: client,
	}
}

/*DeleteAclsRidUsersUIDActionParams contains all the parameters to send to the API endpoint
for the delete acls rid users UID action operation typically these are written to a http.Request
*/
type DeleteAclsRidUsersUIDActionParams struct {

	/*Action
	  action name

	*/
	Action string
	/*Rid
	  resource ID.

	*/
	Rid string
	/*UID
	  account ID.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithTimeout(timeout time.Duration) *DeleteAclsRidUsersUIDActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithContext(ctx context.Context) *DeleteAclsRidUsersUIDActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithHTTPClient(client *http.Client) *DeleteAclsRidUsersUIDActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithAction(action string) *DeleteAclsRidUsersUIDActionParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetAction(action string) {
	o.Action = action
}

// WithRid adds the rid to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithRid(rid string) *DeleteAclsRidUsersUIDActionParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetRid(rid string) {
	o.Rid = rid
}

// WithUID adds the uid to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) WithUID(uid string) *DeleteAclsRidUsersUIDActionParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the delete acls rid users UID action params
func (o *DeleteAclsRidUsersUIDActionParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAclsRidUsersUIDActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param action
	if err := r.SetPathParam("action", o.Action); err != nil {
		return err
	}

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
