// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAclsRidGroupsGidParams creates a new DeleteAclsRidGroupsGidParams object
// with the default values initialized.
func NewDeleteAclsRidGroupsGidParams() *DeleteAclsRidGroupsGidParams {
	var ()
	return &DeleteAclsRidGroupsGidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAclsRidGroupsGidParamsWithTimeout creates a new DeleteAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAclsRidGroupsGidParamsWithTimeout(timeout time.Duration) *DeleteAclsRidGroupsGidParams {
	var ()
	return &DeleteAclsRidGroupsGidParams{

		timeout: timeout,
	}
}

// NewDeleteAclsRidGroupsGidParamsWithContext creates a new DeleteAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAclsRidGroupsGidParamsWithContext(ctx context.Context) *DeleteAclsRidGroupsGidParams {
	var ()
	return &DeleteAclsRidGroupsGidParams{

		Context: ctx,
	}
}

// NewDeleteAclsRidGroupsGidParamsWithHTTPClient creates a new DeleteAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAclsRidGroupsGidParamsWithHTTPClient(client *http.Client) *DeleteAclsRidGroupsGidParams {
	var ()
	return &DeleteAclsRidGroupsGidParams{
		HTTPClient: client,
	}
}

/*DeleteAclsRidGroupsGidParams contains all the parameters to send to the API endpoint
for the delete acls rid groups gid operation typically these are written to a http.Request
*/
type DeleteAclsRidGroupsGidParams struct {

	/*Gid
	  group ID.

	*/
	Gid string
	/*Rid
	  resource ID.

	*/
	Rid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) WithTimeout(timeout time.Duration) *DeleteAclsRidGroupsGidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) WithContext(ctx context.Context) *DeleteAclsRidGroupsGidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) WithHTTPClient(client *http.Client) *DeleteAclsRidGroupsGidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGid adds the gid to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) WithGid(gid string) *DeleteAclsRidGroupsGidParams {
	o.SetGid(gid)
	return o
}

// SetGid adds the gid to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) SetGid(gid string) {
	o.Gid = gid
}

// WithRid adds the rid to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) WithRid(rid string) *DeleteAclsRidGroupsGidParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the delete acls rid groups gid params
func (o *DeleteAclsRidGroupsGidParams) SetRid(rid string) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAclsRidGroupsGidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gid
	if err := r.SetPathParam("gid", o.Gid); err != nil {
		return err
	}

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
