// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAclsRidReader is a Reader for the DeleteAclsRid structure.
type DeleteAclsRidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAclsRidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAclsRidNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteAclsRidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAclsRidNoContent creates a DeleteAclsRidNoContent with default headers values
func NewDeleteAclsRidNoContent() *DeleteAclsRidNoContent {
	return &DeleteAclsRidNoContent{}
}

/*DeleteAclsRidNoContent handles this case with default header values.

Success.
*/
type DeleteAclsRidNoContent struct {
}

func (o *DeleteAclsRidNoContent) Error() string {
	return fmt.Sprintf("[DELETE /acls/{rid}][%d] deleteAclsRidNoContent ", 204)
}

func (o *DeleteAclsRidNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAclsRidNotFound creates a DeleteAclsRidNotFound with default headers values
func NewDeleteAclsRidNotFound() *DeleteAclsRidNotFound {
	return &DeleteAclsRidNotFound{}
}

/*DeleteAclsRidNotFound handles this case with default header values.

ACL not found.
*/
type DeleteAclsRidNotFound struct {
}

func (o *DeleteAclsRidNotFound) Error() string {
	return fmt.Sprintf("[DELETE /acls/{rid}][%d] deleteAclsRidNotFound ", 404)
}

func (o *DeleteAclsRidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
