// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAclsRidGroupsGidParams creates a new GetAclsRidGroupsGidParams object
// with the default values initialized.
func NewGetAclsRidGroupsGidParams() *GetAclsRidGroupsGidParams {
	var ()
	return &GetAclsRidGroupsGidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAclsRidGroupsGidParamsWithTimeout creates a new GetAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAclsRidGroupsGidParamsWithTimeout(timeout time.Duration) *GetAclsRidGroupsGidParams {
	var ()
	return &GetAclsRidGroupsGidParams{

		timeout: timeout,
	}
}

// NewGetAclsRidGroupsGidParamsWithContext creates a new GetAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAclsRidGroupsGidParamsWithContext(ctx context.Context) *GetAclsRidGroupsGidParams {
	var ()
	return &GetAclsRidGroupsGidParams{

		Context: ctx,
	}
}

// NewGetAclsRidGroupsGidParamsWithHTTPClient creates a new GetAclsRidGroupsGidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAclsRidGroupsGidParamsWithHTTPClient(client *http.Client) *GetAclsRidGroupsGidParams {
	var ()
	return &GetAclsRidGroupsGidParams{
		HTTPClient: client,
	}
}

/*GetAclsRidGroupsGidParams contains all the parameters to send to the API endpoint
for the get acls rid groups gid operation typically these are written to a http.Request
*/
type GetAclsRidGroupsGidParams struct {

	/*Gid
	  group ID

	*/
	Gid string
	/*Rid
	  resource ID

	*/
	Rid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) WithTimeout(timeout time.Duration) *GetAclsRidGroupsGidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) WithContext(ctx context.Context) *GetAclsRidGroupsGidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) WithHTTPClient(client *http.Client) *GetAclsRidGroupsGidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGid adds the gid to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) WithGid(gid string) *GetAclsRidGroupsGidParams {
	o.SetGid(gid)
	return o
}

// SetGid adds the gid to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) SetGid(gid string) {
	o.Gid = gid
}

// WithRid adds the rid to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) WithRid(rid string) *GetAclsRidGroupsGidParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the get acls rid groups gid params
func (o *GetAclsRidGroupsGidParams) SetRid(rid string) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAclsRidGroupsGidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gid
	if err := r.SetPathParam("gid", o.Gid); err != nil {
		return err
	}

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
