// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAclsRidUsersUIDActionParams creates a new GetAclsRidUsersUIDActionParams object
// with the default values initialized.
func NewGetAclsRidUsersUIDActionParams() *GetAclsRidUsersUIDActionParams {
	var ()
	return &GetAclsRidUsersUIDActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAclsRidUsersUIDActionParamsWithTimeout creates a new GetAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAclsRidUsersUIDActionParamsWithTimeout(timeout time.Duration) *GetAclsRidUsersUIDActionParams {
	var ()
	return &GetAclsRidUsersUIDActionParams{

		timeout: timeout,
	}
}

// NewGetAclsRidUsersUIDActionParamsWithContext creates a new GetAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAclsRidUsersUIDActionParamsWithContext(ctx context.Context) *GetAclsRidUsersUIDActionParams {
	var ()
	return &GetAclsRidUsersUIDActionParams{

		Context: ctx,
	}
}

// NewGetAclsRidUsersUIDActionParamsWithHTTPClient creates a new GetAclsRidUsersUIDActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAclsRidUsersUIDActionParamsWithHTTPClient(client *http.Client) *GetAclsRidUsersUIDActionParams {
	var ()
	return &GetAclsRidUsersUIDActionParams{
		HTTPClient: client,
	}
}

/*GetAclsRidUsersUIDActionParams contains all the parameters to send to the API endpoint
for the get acls rid users UID action operation typically these are written to a http.Request
*/
type GetAclsRidUsersUIDActionParams struct {

	/*Action
	  action name

	*/
	Action string
	/*Rid
	  resource ID

	*/
	Rid string
	/*UID
	  account ID

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithTimeout(timeout time.Duration) *GetAclsRidUsersUIDActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithContext(ctx context.Context) *GetAclsRidUsersUIDActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithHTTPClient(client *http.Client) *GetAclsRidUsersUIDActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithAction(action string) *GetAclsRidUsersUIDActionParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetAction(action string) {
	o.Action = action
}

// WithRid adds the rid to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithRid(rid string) *GetAclsRidUsersUIDActionParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetRid(rid string) {
	o.Rid = rid
}

// WithUID adds the uid to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) WithUID(uid string) *GetAclsRidUsersUIDActionParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the get acls rid users UID action params
func (o *GetAclsRidUsersUIDActionParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAclsRidUsersUIDActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param action
	if err := r.SetPathParam("action", o.Action); err != nil {
		return err
	}

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
