// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAclsRidParams creates a new GetAclsRidParams object
// with the default values initialized.
func NewGetAclsRidParams() *GetAclsRidParams {
	var ()
	return &GetAclsRidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAclsRidParamsWithTimeout creates a new GetAclsRidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAclsRidParamsWithTimeout(timeout time.Duration) *GetAclsRidParams {
	var ()
	return &GetAclsRidParams{

		timeout: timeout,
	}
}

// NewGetAclsRidParamsWithContext creates a new GetAclsRidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAclsRidParamsWithContext(ctx context.Context) *GetAclsRidParams {
	var ()
	return &GetAclsRidParams{

		Context: ctx,
	}
}

// NewGetAclsRidParamsWithHTTPClient creates a new GetAclsRidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAclsRidParamsWithHTTPClient(client *http.Client) *GetAclsRidParams {
	var ()
	return &GetAclsRidParams{
		HTTPClient: client,
	}
}

/*GetAclsRidParams contains all the parameters to send to the API endpoint
for the get acls rid operation typically these are written to a http.Request
*/
type GetAclsRidParams struct {

	/*Rid
	  The ID of the resource to retrieve the ACL for.

	*/
	Rid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acls rid params
func (o *GetAclsRidParams) WithTimeout(timeout time.Duration) *GetAclsRidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acls rid params
func (o *GetAclsRidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acls rid params
func (o *GetAclsRidParams) WithContext(ctx context.Context) *GetAclsRidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acls rid params
func (o *GetAclsRidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acls rid params
func (o *GetAclsRidParams) WithHTTPClient(client *http.Client) *GetAclsRidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acls rid params
func (o *GetAclsRidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRid adds the rid to the get acls rid params
func (o *GetAclsRidParams) WithRid(rid string) *GetAclsRidParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the get acls rid params
func (o *GetAclsRidParams) SetRid(rid string) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAclsRidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
