// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAclsRidUsersUIDParams creates a new GetAclsRidUsersUIDParams object
// with the default values initialized.
func NewGetAclsRidUsersUIDParams() *GetAclsRidUsersUIDParams {
	var ()
	return &GetAclsRidUsersUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAclsRidUsersUIDParamsWithTimeout creates a new GetAclsRidUsersUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAclsRidUsersUIDParamsWithTimeout(timeout time.Duration) *GetAclsRidUsersUIDParams {
	var ()
	return &GetAclsRidUsersUIDParams{

		timeout: timeout,
	}
}

// NewGetAclsRidUsersUIDParamsWithContext creates a new GetAclsRidUsersUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAclsRidUsersUIDParamsWithContext(ctx context.Context) *GetAclsRidUsersUIDParams {
	var ()
	return &GetAclsRidUsersUIDParams{

		Context: ctx,
	}
}

// NewGetAclsRidUsersUIDParamsWithHTTPClient creates a new GetAclsRidUsersUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAclsRidUsersUIDParamsWithHTTPClient(client *http.Client) *GetAclsRidUsersUIDParams {
	var ()
	return &GetAclsRidUsersUIDParams{
		HTTPClient: client,
	}
}

/*GetAclsRidUsersUIDParams contains all the parameters to send to the API endpoint
for the get acls rid users UID operation typically these are written to a http.Request
*/
type GetAclsRidUsersUIDParams struct {

	/*Rid
	  resource ID

	*/
	Rid string
	/*UID
	  account ID

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) WithTimeout(timeout time.Duration) *GetAclsRidUsersUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) WithContext(ctx context.Context) *GetAclsRidUsersUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) WithHTTPClient(client *http.Client) *GetAclsRidUsersUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRid adds the rid to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) WithRid(rid string) *GetAclsRidUsersUIDParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) SetRid(rid string) {
	o.Rid = rid
}

// WithUID adds the uid to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) WithUID(uid string) *GetAclsRidUsersUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the get acls rid users UID params
func (o *GetAclsRidUsersUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAclsRidUsersUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
