// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// GetAclsRidUsersUIDActionReader is a Reader for the GetAclsRidUsersUIDAction structure.
type GetAclsRidUsersUIDActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAclsRidUsersUIDActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAclsRidUsersUIDActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAclsRidUsersUIDActionOK creates a GetAclsRidUsersUIDActionOK with default headers values
func NewGetAclsRidUsersUIDActionOK() *GetAclsRidUsersUIDActionOK {
	return &GetAclsRidUsersUIDActionOK{}
}

/*GetAclsRidUsersUIDActionOK handles this case with default header values.

Boolean answer in JSON response body.
*/
type GetAclsRidUsersUIDActionOK struct {
	Payload *models.ActionAllowed
}

func (o *GetAclsRidUsersUIDActionOK) Error() string {
	return fmt.Sprintf("[GET /acls/{rid}/users/{uid}/{action}][%d] getAclsRidUsersUidActionOK  %+v", 200, o.Payload)
}

func (o *GetAclsRidUsersUIDActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActionAllowed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
