// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// NewPatchAclsRidParams creates a new PatchAclsRidParams object
// with the default values initialized.
func NewPatchAclsRidParams() *PatchAclsRidParams {
	var ()
	return &PatchAclsRidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAclsRidParamsWithTimeout creates a new PatchAclsRidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAclsRidParamsWithTimeout(timeout time.Duration) *PatchAclsRidParams {
	var ()
	return &PatchAclsRidParams{

		timeout: timeout,
	}
}

// NewPatchAclsRidParamsWithContext creates a new PatchAclsRidParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAclsRidParamsWithContext(ctx context.Context) *PatchAclsRidParams {
	var ()
	return &PatchAclsRidParams{

		Context: ctx,
	}
}

// NewPatchAclsRidParamsWithHTTPClient creates a new PatchAclsRidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAclsRidParamsWithHTTPClient(client *http.Client) *PatchAclsRidParams {
	var ()
	return &PatchAclsRidParams{
		HTTPClient: client,
	}
}

/*PatchAclsRidParams contains all the parameters to send to the API endpoint
for the patch acls rid operation typically these are written to a http.Request
*/
type PatchAclsRidParams struct {

	/*ACLUpdateObject
	  New ACL.

	*/
	ACLUpdateObject *models.ACLUpdate
	/*Rid
	  The ID of the resource for which the ACL should be created.

	*/
	Rid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch acls rid params
func (o *PatchAclsRidParams) WithTimeout(timeout time.Duration) *PatchAclsRidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch acls rid params
func (o *PatchAclsRidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch acls rid params
func (o *PatchAclsRidParams) WithContext(ctx context.Context) *PatchAclsRidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch acls rid params
func (o *PatchAclsRidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch acls rid params
func (o *PatchAclsRidParams) WithHTTPClient(client *http.Client) *PatchAclsRidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch acls rid params
func (o *PatchAclsRidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACLUpdateObject adds the aCLUpdateObject to the patch acls rid params
func (o *PatchAclsRidParams) WithACLUpdateObject(aCLUpdateObject *models.ACLUpdate) *PatchAclsRidParams {
	o.SetACLUpdateObject(aCLUpdateObject)
	return o
}

// SetACLUpdateObject adds the aclUpdateObject to the patch acls rid params
func (o *PatchAclsRidParams) SetACLUpdateObject(aCLUpdateObject *models.ACLUpdate) {
	o.ACLUpdateObject = aCLUpdateObject
}

// WithRid adds the rid to the patch acls rid params
func (o *PatchAclsRidParams) WithRid(rid string) *PatchAclsRidParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the patch acls rid params
func (o *PatchAclsRidParams) SetRid(rid string) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAclsRidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ACLUpdateObject != nil {
		if err := r.SetBodyParam(o.ACLUpdateObject); err != nil {
			return err
		}
	}

	// path param rid
	if err := r.SetPathParam("rid", o.Rid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
