// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAclsRidGroupsGidActionReader is a Reader for the PutAclsRidGroupsGidAction structure.
type PutAclsRidGroupsGidActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAclsRidGroupsGidActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutAclsRidGroupsGidActionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAclsRidGroupsGidActionNoContent creates a PutAclsRidGroupsGidActionNoContent with default headers values
func NewPutAclsRidGroupsGidActionNoContent() *PutAclsRidGroupsGidActionNoContent {
	return &PutAclsRidGroupsGidActionNoContent{}
}

/*PutAclsRidGroupsGidActionNoContent handles this case with default header values.

Success.
*/
type PutAclsRidGroupsGidActionNoContent struct {
}

func (o *PutAclsRidGroupsGidActionNoContent) Error() string {
	return fmt.Sprintf("[PUT /acls/{rid}/groups/{gid}/{action}][%d] putAclsRidGroupsGidActionNoContent ", 204)
}

func (o *PutAclsRidGroupsGidActionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
