// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAclsRidUsersUIDActionReader is a Reader for the PutAclsRidUsersUIDAction structure.
type PutAclsRidUsersUIDActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAclsRidUsersUIDActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutAclsRidUsersUIDActionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPutAclsRidUsersUIDActionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAclsRidUsersUIDActionNoContent creates a PutAclsRidUsersUIDActionNoContent with default headers values
func NewPutAclsRidUsersUIDActionNoContent() *PutAclsRidUsersUIDActionNoContent {
	return &PutAclsRidUsersUIDActionNoContent{}
}

/*PutAclsRidUsersUIDActionNoContent handles this case with default header values.

Success.
*/
type PutAclsRidUsersUIDActionNoContent struct {
}

func (o *PutAclsRidUsersUIDActionNoContent) Error() string {
	return fmt.Sprintf("[PUT /acls/{rid}/users/{uid}/{action}][%d] putAclsRidUsersUidActionNoContent ", 204)
}

func (o *PutAclsRidUsersUIDActionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAclsRidUsersUIDActionConflict creates a PutAclsRidUsersUIDActionConflict with default headers values
func NewPutAclsRidUsersUIDActionConflict() *PutAclsRidUsersUIDActionConflict {
	return &PutAclsRidUsersUIDActionConflict{}
}

/*PutAclsRidUsersUIDActionConflict handles this case with default header values.

Already exists (this account already has this action).
*/
type PutAclsRidUsersUIDActionConflict struct {
}

func (o *PutAclsRidUsersUIDActionConflict) Error() string {
	return fmt.Sprintf("[PUT /acls/{rid}/users/{uid}/{action}][%d] putAclsRidUsersUidActionConflict ", 409)
}

func (o *PutAclsRidUsersUIDActionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
