// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAuthOidcProvidersProviderIDParams creates a new DeleteAuthOidcProvidersProviderIDParams object
// with the default values initialized.
func NewDeleteAuthOidcProvidersProviderIDParams() *DeleteAuthOidcProvidersProviderIDParams {
	var ()
	return &DeleteAuthOidcProvidersProviderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAuthOidcProvidersProviderIDParamsWithTimeout creates a new DeleteAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAuthOidcProvidersProviderIDParamsWithTimeout(timeout time.Duration) *DeleteAuthOidcProvidersProviderIDParams {
	var ()
	return &DeleteAuthOidcProvidersProviderIDParams{

		timeout: timeout,
	}
}

// NewDeleteAuthOidcProvidersProviderIDParamsWithContext creates a new DeleteAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAuthOidcProvidersProviderIDParamsWithContext(ctx context.Context) *DeleteAuthOidcProvidersProviderIDParams {
	var ()
	return &DeleteAuthOidcProvidersProviderIDParams{

		Context: ctx,
	}
}

// NewDeleteAuthOidcProvidersProviderIDParamsWithHTTPClient creates a new DeleteAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAuthOidcProvidersProviderIDParamsWithHTTPClient(client *http.Client) *DeleteAuthOidcProvidersProviderIDParams {
	var ()
	return &DeleteAuthOidcProvidersProviderIDParams{
		HTTPClient: client,
	}
}

/*DeleteAuthOidcProvidersProviderIDParams contains all the parameters to send to the API endpoint
for the delete auth oidc providers provider ID operation typically these are written to a http.Request
*/
type DeleteAuthOidcProvidersProviderIDParams struct {

	/*ProviderID
	  The ID of the OIDC provider to delete.

	*/
	ProviderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) WithTimeout(timeout time.Duration) *DeleteAuthOidcProvidersProviderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) WithContext(ctx context.Context) *DeleteAuthOidcProvidersProviderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) WithHTTPClient(client *http.Client) *DeleteAuthOidcProvidersProviderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderID adds the providerID to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) WithProviderID(providerID string) *DeleteAuthOidcProvidersProviderIDParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the delete auth oidc providers provider ID params
func (o *DeleteAuthOidcProvidersProviderIDParams) SetProviderID(providerID string) {
	o.ProviderID = providerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAuthOidcProvidersProviderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider-id
	if err := r.SetPathParam("provider-id", o.ProviderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
