// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAuthOidcProvidersProviderIDReader is a Reader for the DeleteAuthOidcProvidersProviderID structure.
type DeleteAuthOidcProvidersProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAuthOidcProvidersProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAuthOidcProvidersProviderIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAuthOidcProvidersProviderIDNoContent creates a DeleteAuthOidcProvidersProviderIDNoContent with default headers values
func NewDeleteAuthOidcProvidersProviderIDNoContent() *DeleteAuthOidcProvidersProviderIDNoContent {
	return &DeleteAuthOidcProvidersProviderIDNoContent{}
}

/*DeleteAuthOidcProvidersProviderIDNoContent handles this case with default header values.

Success.
*/
type DeleteAuthOidcProvidersProviderIDNoContent struct {
}

func (o *DeleteAuthOidcProvidersProviderIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /auth/oidc/providers/{provider-id}][%d] deleteAuthOidcProvidersProviderIdNoContent ", 204)
}

func (o *DeleteAuthOidcProvidersProviderIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
