// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthOidcProvidersProviderIDParams creates a new GetAuthOidcProvidersProviderIDParams object
// with the default values initialized.
func NewGetAuthOidcProvidersProviderIDParams() *GetAuthOidcProvidersProviderIDParams {
	var ()
	return &GetAuthOidcProvidersProviderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthOidcProvidersProviderIDParamsWithTimeout creates a new GetAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthOidcProvidersProviderIDParamsWithTimeout(timeout time.Duration) *GetAuthOidcProvidersProviderIDParams {
	var ()
	return &GetAuthOidcProvidersProviderIDParams{

		timeout: timeout,
	}
}

// NewGetAuthOidcProvidersProviderIDParamsWithContext creates a new GetAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthOidcProvidersProviderIDParamsWithContext(ctx context.Context) *GetAuthOidcProvidersProviderIDParams {
	var ()
	return &GetAuthOidcProvidersProviderIDParams{

		Context: ctx,
	}
}

// NewGetAuthOidcProvidersProviderIDParamsWithHTTPClient creates a new GetAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthOidcProvidersProviderIDParamsWithHTTPClient(client *http.Client) *GetAuthOidcProvidersProviderIDParams {
	var ()
	return &GetAuthOidcProvidersProviderIDParams{
		HTTPClient: client,
	}
}

/*GetAuthOidcProvidersProviderIDParams contains all the parameters to send to the API endpoint
for the get auth oidc providers provider ID operation typically these are written to a http.Request
*/
type GetAuthOidcProvidersProviderIDParams struct {

	/*ProviderID
	  The ID of the OIDC provider to retrieve the config for.

	*/
	ProviderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) WithTimeout(timeout time.Duration) *GetAuthOidcProvidersProviderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) WithContext(ctx context.Context) *GetAuthOidcProvidersProviderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) WithHTTPClient(client *http.Client) *GetAuthOidcProvidersProviderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderID adds the providerID to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) WithProviderID(providerID string) *GetAuthOidcProvidersProviderIDParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the get auth oidc providers provider ID params
func (o *GetAuthOidcProvidersProviderIDParams) SetProviderID(providerID string) {
	o.ProviderID = providerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthOidcProvidersProviderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider-id
	if err := r.SetPathParam("provider-id", o.ProviderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
