// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAuthOidcProvidersReader is a Reader for the GetAuthOidcProviders structure.
type GetAuthOidcProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthOidcProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthOidcProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthOidcProvidersOK creates a GetAuthOidcProvidersOK with default headers values
func NewGetAuthOidcProvidersOK() *GetAuthOidcProvidersOK {
	return &GetAuthOidcProvidersOK{}
}

/*GetAuthOidcProvidersOK handles this case with default header values.

Success.
*/
type GetAuthOidcProvidersOK struct {
}

func (o *GetAuthOidcProvidersOK) Error() string {
	return fmt.Sprintf("[GET /auth/oidc/providers][%d] getAuthOidcProvidersOK ", 200)
}

func (o *GetAuthOidcProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
