// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthOidcProvidersParams creates a new GetAuthOidcProvidersParams object
// with the default values initialized.
func NewGetAuthOidcProvidersParams() *GetAuthOidcProvidersParams {

	return &GetAuthOidcProvidersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthOidcProvidersParamsWithTimeout creates a new GetAuthOidcProvidersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthOidcProvidersParamsWithTimeout(timeout time.Duration) *GetAuthOidcProvidersParams {

	return &GetAuthOidcProvidersParams{

		timeout: timeout,
	}
}

// NewGetAuthOidcProvidersParamsWithContext creates a new GetAuthOidcProvidersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthOidcProvidersParamsWithContext(ctx context.Context) *GetAuthOidcProvidersParams {

	return &GetAuthOidcProvidersParams{

		Context: ctx,
	}
}

// NewGetAuthOidcProvidersParamsWithHTTPClient creates a new GetAuthOidcProvidersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthOidcProvidersParamsWithHTTPClient(client *http.Client) *GetAuthOidcProvidersParams {

	return &GetAuthOidcProvidersParams{
		HTTPClient: client,
	}
}

/*GetAuthOidcProvidersParams contains all the parameters to send to the API endpoint
for the get auth oidc providers operation typically these are written to a http.Request
*/
type GetAuthOidcProvidersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) WithTimeout(timeout time.Duration) *GetAuthOidcProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) WithContext(ctx context.Context) *GetAuthOidcProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) WithHTTPClient(client *http.Client) *GetAuthOidcProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth oidc providers params
func (o *GetAuthOidcProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthOidcProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
