// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// NewPatchAuthOidcProvidersProviderIDParams creates a new PatchAuthOidcProvidersProviderIDParams object
// with the default values initialized.
func NewPatchAuthOidcProvidersProviderIDParams() *PatchAuthOidcProvidersProviderIDParams {
	var ()
	return &PatchAuthOidcProvidersProviderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAuthOidcProvidersProviderIDParamsWithTimeout creates a new PatchAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAuthOidcProvidersProviderIDParamsWithTimeout(timeout time.Duration) *PatchAuthOidcProvidersProviderIDParams {
	var ()
	return &PatchAuthOidcProvidersProviderIDParams{

		timeout: timeout,
	}
}

// NewPatchAuthOidcProvidersProviderIDParamsWithContext creates a new PatchAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAuthOidcProvidersProviderIDParamsWithContext(ctx context.Context) *PatchAuthOidcProvidersProviderIDParams {
	var ()
	return &PatchAuthOidcProvidersProviderIDParams{

		Context: ctx,
	}
}

// NewPatchAuthOidcProvidersProviderIDParamsWithHTTPClient creates a new PatchAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAuthOidcProvidersProviderIDParamsWithHTTPClient(client *http.Client) *PatchAuthOidcProvidersProviderIDParams {
	var ()
	return &PatchAuthOidcProvidersProviderIDParams{
		HTTPClient: client,
	}
}

/*PatchAuthOidcProvidersProviderIDParams contains all the parameters to send to the API endpoint
for the patch auth oidc providers provider ID operation typically these are written to a http.Request
*/
type PatchAuthOidcProvidersProviderIDParams struct {

	/*ProviderConfigObject
	  Provider config JSON object

	*/
	ProviderConfigObject *models.OIDCProviderConfig
	/*ProviderID
	  The ID of the provider to modify.

	*/
	ProviderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) WithTimeout(timeout time.Duration) *PatchAuthOidcProvidersProviderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) WithContext(ctx context.Context) *PatchAuthOidcProvidersProviderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) WithHTTPClient(client *http.Client) *PatchAuthOidcProvidersProviderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderConfigObject adds the providerConfigObject to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) WithProviderConfigObject(providerConfigObject *models.OIDCProviderConfig) *PatchAuthOidcProvidersProviderIDParams {
	o.SetProviderConfigObject(providerConfigObject)
	return o
}

// SetProviderConfigObject adds the providerConfigObject to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) SetProviderConfigObject(providerConfigObject *models.OIDCProviderConfig) {
	o.ProviderConfigObject = providerConfigObject
}

// WithProviderID adds the providerID to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) WithProviderID(providerID string) *PatchAuthOidcProvidersProviderIDParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the patch auth oidc providers provider ID params
func (o *PatchAuthOidcProvidersProviderIDParams) SetProviderID(providerID string) {
	o.ProviderID = providerID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAuthOidcProvidersProviderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProviderConfigObject != nil {
		if err := r.SetBodyParam(o.ProviderConfigObject); err != nil {
			return err
		}
	}

	// path param provider-id
	if err := r.SetPathParam("provider-id", o.ProviderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
