// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchAuthOidcProvidersProviderIDReader is a Reader for the PatchAuthOidcProvidersProviderID structure.
type PatchAuthOidcProvidersProviderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAuthOidcProvidersProviderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPatchAuthOidcProvidersProviderIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPatchAuthOidcProvidersProviderIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchAuthOidcProvidersProviderIDNoContent creates a PatchAuthOidcProvidersProviderIDNoContent with default headers values
func NewPatchAuthOidcProvidersProviderIDNoContent() *PatchAuthOidcProvidersProviderIDNoContent {
	return &PatchAuthOidcProvidersProviderIDNoContent{}
}

/*PatchAuthOidcProvidersProviderIDNoContent handles this case with default header values.

Update applied.
*/
type PatchAuthOidcProvidersProviderIDNoContent struct {
}

func (o *PatchAuthOidcProvidersProviderIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /auth/oidc/providers/{provider-id}][%d] patchAuthOidcProvidersProviderIdNoContent ", 204)
}

func (o *PatchAuthOidcProvidersProviderIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchAuthOidcProvidersProviderIDBadRequest creates a PatchAuthOidcProvidersProviderIDBadRequest with default headers values
func NewPatchAuthOidcProvidersProviderIDBadRequest() *PatchAuthOidcProvidersProviderIDBadRequest {
	return &PatchAuthOidcProvidersProviderIDBadRequest{}
}

/*PatchAuthOidcProvidersProviderIDBadRequest handles this case with default header values.

Various errors (e.g. provider not yet configured).
*/
type PatchAuthOidcProvidersProviderIDBadRequest struct {
}

func (o *PatchAuthOidcProvidersProviderIDBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /auth/oidc/providers/{provider-id}][%d] patchAuthOidcProvidersProviderIdBadRequest ", 400)
}

func (o *PatchAuthOidcProvidersProviderIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
