// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// NewPutAuthOidcProvidersProviderIDParams creates a new PutAuthOidcProvidersProviderIDParams object
// with the default values initialized.
func NewPutAuthOidcProvidersProviderIDParams() *PutAuthOidcProvidersProviderIDParams {
	var ()
	return &PutAuthOidcProvidersProviderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAuthOidcProvidersProviderIDParamsWithTimeout creates a new PutAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAuthOidcProvidersProviderIDParamsWithTimeout(timeout time.Duration) *PutAuthOidcProvidersProviderIDParams {
	var ()
	return &PutAuthOidcProvidersProviderIDParams{

		timeout: timeout,
	}
}

// NewPutAuthOidcProvidersProviderIDParamsWithContext creates a new PutAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAuthOidcProvidersProviderIDParamsWithContext(ctx context.Context) *PutAuthOidcProvidersProviderIDParams {
	var ()
	return &PutAuthOidcProvidersProviderIDParams{

		Context: ctx,
	}
}

// NewPutAuthOidcProvidersProviderIDParamsWithHTTPClient creates a new PutAuthOidcProvidersProviderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAuthOidcProvidersProviderIDParamsWithHTTPClient(client *http.Client) *PutAuthOidcProvidersProviderIDParams {
	var ()
	return &PutAuthOidcProvidersProviderIDParams{
		HTTPClient: client,
	}
}

/*PutAuthOidcProvidersProviderIDParams contains all the parameters to send to the API endpoint
for the put auth oidc providers provider ID operation typically these are written to a http.Request
*/
type PutAuthOidcProvidersProviderIDParams struct {

	/*ProviderConfigObject
	  Provider config JSON object

	*/
	ProviderConfigObject *models.OIDCProviderConfig
	/*ProviderID
	  The ID of the provider to create.

	*/
	ProviderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) WithTimeout(timeout time.Duration) *PutAuthOidcProvidersProviderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) WithContext(ctx context.Context) *PutAuthOidcProvidersProviderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) WithHTTPClient(client *http.Client) *PutAuthOidcProvidersProviderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderConfigObject adds the providerConfigObject to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) WithProviderConfigObject(providerConfigObject *models.OIDCProviderConfig) *PutAuthOidcProvidersProviderIDParams {
	o.SetProviderConfigObject(providerConfigObject)
	return o
}

// SetProviderConfigObject adds the providerConfigObject to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) SetProviderConfigObject(providerConfigObject *models.OIDCProviderConfig) {
	o.ProviderConfigObject = providerConfigObject
}

// WithProviderID adds the providerID to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) WithProviderID(providerID string) *PutAuthOidcProvidersProviderIDParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the put auth oidc providers provider ID params
func (o *PutAuthOidcProvidersProviderIDParams) SetProviderID(providerID string) {
	o.ProviderID = providerID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAuthOidcProvidersProviderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProviderConfigObject != nil {
		if err := r.SetBodyParam(o.ProviderConfigObject); err != nil {
			return err
		}
	}

	// path param provider-id
	if err := r.SetPathParam("provider-id", o.ProviderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
