// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/cosmos/models"
)

// NewPackageRepositoryAddParams creates a new PackageRepositoryAddParams object
// with the default values initialized.
func NewPackageRepositoryAddParams() *PackageRepositoryAddParams {
	var ()
	return &PackageRepositoryAddParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPackageRepositoryAddParamsWithTimeout creates a new PackageRepositoryAddParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPackageRepositoryAddParamsWithTimeout(timeout time.Duration) *PackageRepositoryAddParams {
	var ()
	return &PackageRepositoryAddParams{

		timeout: timeout,
	}
}

// NewPackageRepositoryAddParamsWithContext creates a new PackageRepositoryAddParams object
// with the default values initialized, and the ability to set a context for a request
func NewPackageRepositoryAddParamsWithContext(ctx context.Context) *PackageRepositoryAddParams {
	var ()
	return &PackageRepositoryAddParams{

		Context: ctx,
	}
}

// NewPackageRepositoryAddParamsWithHTTPClient creates a new PackageRepositoryAddParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPackageRepositoryAddParamsWithHTTPClient(client *http.Client) *PackageRepositoryAddParams {
	var ()
	return &PackageRepositoryAddParams{
		HTTPClient: client,
	}
}

/*PackageRepositoryAddParams contains all the parameters to send to the API endpoint
for the package repository add operation typically these are written to a http.Request
*/
type PackageRepositoryAddParams struct {

	/*Body*/
	Body *models.PackageAddRepoRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the package repository add params
func (o *PackageRepositoryAddParams) WithTimeout(timeout time.Duration) *PackageRepositoryAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the package repository add params
func (o *PackageRepositoryAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the package repository add params
func (o *PackageRepositoryAddParams) WithContext(ctx context.Context) *PackageRepositoryAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the package repository add params
func (o *PackageRepositoryAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the package repository add params
func (o *PackageRepositoryAddParams) WithHTTPClient(client *http.Client) *PackageRepositoryAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the package repository add params
func (o *PackageRepositoryAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the package repository add params
func (o *PackageRepositoryAddParams) WithBody(body *models.PackageAddRepoRequest) *PackageRepositoryAddParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the package repository add params
func (o *PackageRepositoryAddParams) SetBody(body *models.PackageAddRepoRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PackageRepositoryAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
