// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/cosmos/models"
)

// PackageSearchReader is a Reader for the PackageSearch structure.
type PackageSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PackageSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPackageSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPackageSearchOK creates a PackageSearchOK with default headers values
func NewPackageSearchOK() *PackageSearchOK {
	return &PackageSearchOK{}
}

/*PackageSearchOK handles this case with default header values.

PackageSearchOK package search o k
*/
type PackageSearchOK struct {
	Payload *models.SearchResponse
}

func (o *PackageSearchOK) Error() string {
	return fmt.Sprintf("[POST /package/search][%d] packageSearchOK  %+v", 200, o.Payload)
}

func (o *PackageSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
