// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LDApimportGroupObject l d apimport group object
// swagger:model LDAPImportGroupObject
type LDApimportGroupObject struct {

	// groupname
	// Required: true
	Groupname *string `json:"groupname"`
}

// Validate validates this l d apimport group object
func (m *LDApimportGroupObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupname(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LDApimportGroupObject) validateGroupname(formats strfmt.Registry) error {

	if err := validate.Required("groupname", "body", m.Groupname); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LDApimportGroupObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LDApimportGroupObject) UnmarshalBinary(b []byte) error {
	var res LDApimportGroupObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
