// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SAMLACSCallbackURLObject s a m l a c s callback Url object
// swagger:model SAMLACSCallbackUrlObject
type SAMLACSCallbackURLObject struct {

	// acs callback url
	// Required: true
	AcsCallbackURL *string `json:"acs-callback-url"`
}

// Validate validates this s a m l a c s callback Url object
func (m *SAMLACSCallbackURLObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcsCallbackURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SAMLACSCallbackURLObject) validateAcsCallbackURL(formats strfmt.Registry) error {

	if err := validate.Required("acs-callback-url", "body", m.AcsCallbackURL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SAMLACSCallbackURLObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SAMLACSCallbackURLObject) UnmarshalBinary(b []byte) error {
	var res SAMLACSCallbackURLObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
