// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserCreate user create
// swagger:model UserCreate
type UserCreate struct {

	// cluster url
	ClusterURL string `json:"cluster_url,omitempty"`

	// creator uid
	CreatorUID string `json:"creator_uid,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// provider id
	ProviderID string `json:"provider_id,omitempty"`

	// provider type
	ProviderType string `json:"provider_type,omitempty"`

	// public key
	PublicKey string `json:"public_key,omitempty"`
}

// Validate validates this user create
func (m *UserCreate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreate) UnmarshalBinary(b []byte) error {
	var res UserCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
