// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSecretParams creates a new DeleteSecretParams object
// with the default values initialized.
func NewDeleteSecretParams() *DeleteSecretParams {
	var ()
	return &DeleteSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSecretParamsWithTimeout creates a new DeleteSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSecretParamsWithTimeout(timeout time.Duration) *DeleteSecretParams {
	var ()
	return &DeleteSecretParams{

		timeout: timeout,
	}
}

// NewDeleteSecretParamsWithContext creates a new DeleteSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSecretParamsWithContext(ctx context.Context) *DeleteSecretParams {
	var ()
	return &DeleteSecretParams{

		Context: ctx,
	}
}

// NewDeleteSecretParamsWithHTTPClient creates a new DeleteSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSecretParamsWithHTTPClient(client *http.Client) *DeleteSecretParams {
	var ()
	return &DeleteSecretParams{
		HTTPClient: client,
	}
}

/*DeleteSecretParams contains all the parameters to send to the API endpoint
for the delete secret operation typically these are written to a http.Request
*/
type DeleteSecretParams struct {

	/*PathToSecret
	  The path to the secret to delete.

	*/
	PathToSecret string
	/*Store
	  The backend to delete the secret from.

	*/
	Store string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete secret params
func (o *DeleteSecretParams) WithTimeout(timeout time.Duration) *DeleteSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete secret params
func (o *DeleteSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete secret params
func (o *DeleteSecretParams) WithContext(ctx context.Context) *DeleteSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete secret params
func (o *DeleteSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete secret params
func (o *DeleteSecretParams) WithHTTPClient(client *http.Client) *DeleteSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete secret params
func (o *DeleteSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPathToSecret adds the pathToSecret to the delete secret params
func (o *DeleteSecretParams) WithPathToSecret(pathToSecret string) *DeleteSecretParams {
	o.SetPathToSecret(pathToSecret)
	return o
}

// SetPathToSecret adds the pathToSecret to the delete secret params
func (o *DeleteSecretParams) SetPathToSecret(pathToSecret string) {
	o.PathToSecret = pathToSecret
}

// WithStore adds the store to the delete secret params
func (o *DeleteSecretParams) WithStore(store string) *DeleteSecretParams {
	o.SetStore(store)
	return o
}

// SetStore adds the store to the delete secret params
func (o *DeleteSecretParams) SetStore(store string) {
	o.Store = store
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param path-to-secret
	if err := r.SetPathParam("path-to-secret", o.PathToSecret); err != nil {
		return err
	}

	// path param store
	if err := r.SetPathParam("store", o.Store); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
