// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Images images
// swagger:model images
type Images struct {

	// PNG icon URL, preferably 256 by 256 pixels.
	IconLarge string `json:"icon-large,omitempty"`

	// PNG icon URL, preferably 128 by 128 pixels.
	IconMedium string `json:"icon-medium,omitempty"`

	// PNG icon URL, preferably 48 by 48 pixels.
	IconSmall string `json:"icon-small,omitempty"`

	// screenshots
	Screenshots []string `json:"screenshots"`
}

// Validate validates this images
func (m *Images) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Images) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Images) UnmarshalBinary(b []byte) error {
	var res Images
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
