// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Marathon marathon
// swagger:model marathon
type Marathon struct {

	// v2 app mustache template
	// Required: true
	V2AppMustacheTemplate Base64String `json:"v2AppMustacheTemplate"`
}

// Validate validates this marathon
func (m *Marathon) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateV2AppMustacheTemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Marathon) validateV2AppMustacheTemplate(formats strfmt.Registry) error {

	if err := m.V2AppMustacheTemplate.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("v2AppMustacheTemplate")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Marathon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Marathon) UnmarshalBinary(b []byte) error {
	var res Marathon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
