// Code generated by go-swagger; DO NOT EDIT.

package cosmos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new cosmos API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cosmos API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DCOSSystemHealth DC/OS system health.
*/
func (a *Client) DCOSSystemHealth(params *DCOSSystemHealthParams, authInfo runtime.ClientAuthInfoWriter) (*DCOSSystemHealthOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDCOSSystemHealthParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "dcos-system-health",
		Method:             "GET",
		PathPattern:        "/system/health/v1",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DCOSSystemHealthReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DCOSSystemHealthOK), nil

}

/*
DCOSSystemNodes DC/OS nodes.
*/
func (a *Client) DCOSSystemNodes(params *DCOSSystemNodesParams, authInfo runtime.ClientAuthInfoWriter) (*DCOSSystemNodesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDCOSSystemNodesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "dcos-system-nodes",
		Method:             "GET",
		PathPattern:        "/system/health/v1/nodes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DCOSSystemNodesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DCOSSystemNodesOK), nil

}

/*
HealthchechService Healthcheck service.
*/
func (a *Client) HealthchechService(params *HealthchechServiceParams, authInfo runtime.ClientAuthInfoWriter) (*HealthchechServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHealthchechServiceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "healthchech-service",
		Method:             "GET",
		PathPattern:        "/service/{appId}/v1/health",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HealthchechServiceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*HealthchechServiceOK), nil

}

/*
KubernetesAuthData Kuberentes Auth Data
*/
func (a *Client) KubernetesAuthData(params *KubernetesAuthDataParams, authInfo runtime.ClientAuthInfoWriter) (*KubernetesAuthDataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewKubernetesAuthDataParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "kubernetes-auth-data",
		Method:             "GET",
		PathPattern:        "/service/{appId}/v1/auth/data",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &KubernetesAuthDataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*KubernetesAuthDataOK), nil

}

/*
PackageDescribe Show information about the package, including the required resources and configuration to start the service, and command line extensions that are included with the package.
*/
func (a *Client) PackageDescribe(params *PackageDescribeParams, authInfo runtime.ClientAuthInfoWriter) (*PackageDescribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPackageDescribeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "package-describe",
		Method:             "POST",
		PathPattern:        "/package/describe",
		ProducesMediaTypes: []string{"application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v3"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PackageDescribeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PackageDescribeOK), nil

}

/*
PackageInstall Runs a service from a Universe package.
*/
func (a *Client) PackageInstall(params *PackageInstallParams, authInfo runtime.ClientAuthInfoWriter) (*PackageInstallOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPackageInstallParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "package-install",
		Method:             "POST",
		PathPattern:        "/package/install",
		ProducesMediaTypes: []string{"application/vnd.dcos.package.install-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.package.install-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PackageInstallReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PackageInstallOK), nil

}

/*
PackageRepositoryAdd Adds a package repository (for example Universe) for use by DC/OS. To add a package
repository to the beginning of the list set the index to zero (0). To add a package
repository to the end of the list do not specify an index.

*/
func (a *Client) PackageRepositoryAdd(params *PackageRepositoryAddParams, authInfo runtime.ClientAuthInfoWriter) (*PackageRepositoryAddOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPackageRepositoryAddParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "package-repository-add",
		Method:             "POST",
		PathPattern:        "/package/repository/add",
		ProducesMediaTypes: []string{"application/vnd.dcos.package.repository.add-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.package.repository.add-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PackageRepositoryAddReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PackageRepositoryAddOK), nil

}

/*
PackageRepositoryDelete Deletes a package repository (for example Universe) from DC/OS.
*/
func (a *Client) PackageRepositoryDelete(params *PackageRepositoryDeleteParams, authInfo runtime.ClientAuthInfoWriter) (*PackageRepositoryDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPackageRepositoryDeleteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "package-repository-delete",
		Method:             "POST",
		PathPattern:        "/package/repository/delete",
		ProducesMediaTypes: []string{"application/vnd.dcos.package.repository.delete-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.package.repository.delete-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PackageRepositoryDeleteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PackageRepositoryDeleteOK), nil

}

/*
PackageUninstall package uninstall API
*/
func (a *Client) PackageUninstall(params *PackageUninstallParams, authInfo runtime.ClientAuthInfoWriter) (*PackageUninstallOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPackageUninstallParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "package-uninstall",
		Method:             "POST",
		PathPattern:        "/package/uninstall",
		ProducesMediaTypes: []string{"application/vnd.dcos.package.uninstall-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.package.uninstall-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PackageUninstallReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PackageUninstallOK), nil

}

/*
ServiceDescribe Describes a DC/OS Service
*/
func (a *Client) ServiceDescribe(params *ServiceDescribeParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceDescribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceDescribeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service-describe",
		Method:             "POST",
		PathPattern:        "/cosmos/service/describe",
		ProducesMediaTypes: []string{"application/vnd.dcos.service.describe-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.service.describe-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ServiceDescribeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceDescribeOK), nil

}

/*
ServicePlan Service plan.
*/
func (a *Client) ServicePlan(params *ServicePlanParams, authInfo runtime.ClientAuthInfoWriter) (*ServicePlanOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServicePlanParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service-plan",
		Method:             "GET",
		PathPattern:        "/service/{appId}/v1/plans/{plan}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ServicePlanReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServicePlanOK), nil

}

/*
ServiceUpdate Runs a service update.
*/
func (a *Client) ServiceUpdate(params *ServiceUpdateParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceUpdateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service-update",
		Method:             "POST",
		PathPattern:        "/cosmos/service/update",
		ProducesMediaTypes: []string{"application/vnd.dcos.service.update-response+json;charset=utf-8;version=v1"},
		ConsumesMediaTypes: []string{"application/vnd.dcos.service.update-request+json;charset=utf-8;version=v1"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ServiceUpdateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceUpdateOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
