// Code generated by go-swagger; DO NOT EDIT.

package cosmos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDCOSSystemNodesParams creates a new DCOSSystemNodesParams object
// with the default values initialized.
func NewDCOSSystemNodesParams() *DCOSSystemNodesParams {

	return &DCOSSystemNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDCOSSystemNodesParamsWithTimeout creates a new DCOSSystemNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDCOSSystemNodesParamsWithTimeout(timeout time.Duration) *DCOSSystemNodesParams {

	return &DCOSSystemNodesParams{

		timeout: timeout,
	}
}

// NewDCOSSystemNodesParamsWithContext creates a new DCOSSystemNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDCOSSystemNodesParamsWithContext(ctx context.Context) *DCOSSystemNodesParams {

	return &DCOSSystemNodesParams{

		Context: ctx,
	}
}

// NewDCOSSystemNodesParamsWithHTTPClient creates a new DCOSSystemNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDCOSSystemNodesParamsWithHTTPClient(client *http.Client) *DCOSSystemNodesParams {

	return &DCOSSystemNodesParams{
		HTTPClient: client,
	}
}

/*DCOSSystemNodesParams contains all the parameters to send to the API endpoint
for the dcos system nodes operation typically these are written to a http.Request
*/
type DCOSSystemNodesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcos system nodes params
func (o *DCOSSystemNodesParams) WithTimeout(timeout time.Duration) *DCOSSystemNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcos system nodes params
func (o *DCOSSystemNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcos system nodes params
func (o *DCOSSystemNodesParams) WithContext(ctx context.Context) *DCOSSystemNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcos system nodes params
func (o *DCOSSystemNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcos system nodes params
func (o *DCOSSystemNodesParams) WithHTTPClient(client *http.Client) *DCOSSystemNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcos system nodes params
func (o *DCOSSystemNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DCOSSystemNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
