// Code generated by go-swagger; DO NOT EDIT.

package cosmos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	types "github.com/dcos/client-go/dcos/cosmos/types"
)

// NewServiceDescribeParams creates a new ServiceDescribeParams object
// with the default values initialized.
func NewServiceDescribeParams() *ServiceDescribeParams {
	var ()
	return &ServiceDescribeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceDescribeParamsWithTimeout creates a new ServiceDescribeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceDescribeParamsWithTimeout(timeout time.Duration) *ServiceDescribeParams {
	var ()
	return &ServiceDescribeParams{

		timeout: timeout,
	}
}

// NewServiceDescribeParamsWithContext creates a new ServiceDescribeParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceDescribeParamsWithContext(ctx context.Context) *ServiceDescribeParams {
	var ()
	return &ServiceDescribeParams{

		Context: ctx,
	}
}

// NewServiceDescribeParamsWithHTTPClient creates a new ServiceDescribeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServiceDescribeParamsWithHTTPClient(client *http.Client) *ServiceDescribeParams {
	var ()
	return &ServiceDescribeParams{
		HTTPClient: client,
	}
}

/*ServiceDescribeParams contains all the parameters to send to the API endpoint
for the service describe operation typically these are written to a http.Request
*/
type ServiceDescribeParams struct {

	/*Body*/
	Body *types.ServiceDescribeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service describe params
func (o *ServiceDescribeParams) WithTimeout(timeout time.Duration) *ServiceDescribeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service describe params
func (o *ServiceDescribeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service describe params
func (o *ServiceDescribeParams) WithContext(ctx context.Context) *ServiceDescribeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service describe params
func (o *ServiceDescribeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service describe params
func (o *ServiceDescribeParams) WithHTTPClient(client *http.Client) *ServiceDescribeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service describe params
func (o *ServiceDescribeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the service describe params
func (o *ServiceDescribeParams) WithBody(body *types.ServiceDescribeRequest) *ServiceDescribeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the service describe params
func (o *ServiceDescribeParams) SetBody(body *types.ServiceDescribeRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceDescribeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
