/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dcos

type MetronomeV1Job struct {
	CompletedAt *string  `json:"completedAt,omitempty"`
	CreatedAt   string   `json:"createdAt,omitempty"`
	Id          string   `json:"id,omitempty"`
	JobId       string   `json:"jobId,omitempty"`
	Status      string   `json:"status,omitempty"`
	Tasks       []string `json:"tasks,omitempty"`
}
