/*
 * DC/OS
 *
 * DC/OS API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dcos

type V1SystemHealth struct {
	Units                  []V1SystemHealthUnit `json:"units,omitempty"`
	Hostname               string               `json:"hostname,omitempty"`
	Ip                     string               `json:"ip,omitempty"`
	DcosVersion            string               `json:"dcos_version,omitempty"`
	NodeRole               string               `json:"node_role,omitempty"`
	MesosId                string               `json:"mesos_id,omitempty"`
	DcosDiagnosticsVersion string               `json:"dcos_diagnostics_version,omitempty"`
}
