// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthJwksParams creates a new GetAuthJwksParams object
// with the default values initialized.
func NewGetAuthJwksParams() *GetAuthJwksParams {

	return &GetAuthJwksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthJwksParamsWithTimeout creates a new GetAuthJwksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthJwksParamsWithTimeout(timeout time.Duration) *GetAuthJwksParams {

	return &GetAuthJwksParams{

		timeout: timeout,
	}
}

// NewGetAuthJwksParamsWithContext creates a new GetAuthJwksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthJwksParamsWithContext(ctx context.Context) *GetAuthJwksParams {

	return &GetAuthJwksParams{

		Context: ctx,
	}
}

// NewGetAuthJwksParamsWithHTTPClient creates a new GetAuthJwksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthJwksParamsWithHTTPClient(client *http.Client) *GetAuthJwksParams {

	return &GetAuthJwksParams{
		HTTPClient: client,
	}
}

/*GetAuthJwksParams contains all the parameters to send to the API endpoint
for the get auth jwks operation typically these are written to a http.Request
*/
type GetAuthJwksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth jwks params
func (o *GetAuthJwksParams) WithTimeout(timeout time.Duration) *GetAuthJwksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth jwks params
func (o *GetAuthJwksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth jwks params
func (o *GetAuthJwksParams) WithContext(ctx context.Context) *GetAuthJwksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth jwks params
func (o *GetAuthJwksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth jwks params
func (o *GetAuthJwksParams) WithHTTPClient(client *http.Client) *GetAuthJwksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth jwks params
func (o *GetAuthJwksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthJwksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
