// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersUIDParams creates a new GetUsersUIDParams object
// with the default values initialized.
func NewGetUsersUIDParams() *GetUsersUIDParams {
	var ()
	return &GetUsersUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUIDParamsWithTimeout creates a new GetUsersUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersUIDParamsWithTimeout(timeout time.Duration) *GetUsersUIDParams {
	var ()
	return &GetUsersUIDParams{

		timeout: timeout,
	}
}

// NewGetUsersUIDParamsWithContext creates a new GetUsersUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersUIDParamsWithContext(ctx context.Context) *GetUsersUIDParams {
	var ()
	return &GetUsersUIDParams{

		Context: ctx,
	}
}

// NewGetUsersUIDParamsWithHTTPClient creates a new GetUsersUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersUIDParamsWithHTTPClient(client *http.Client) *GetUsersUIDParams {
	var ()
	return &GetUsersUIDParams{
		HTTPClient: client,
	}
}

/*GetUsersUIDParams contains all the parameters to send to the API endpoint
for the get users UID operation typically these are written to a http.Request
*/
type GetUsersUIDParams struct {

	/*UID
	  The ID of the user object to retrieve.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users UID params
func (o *GetUsersUIDParams) WithTimeout(timeout time.Duration) *GetUsersUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users UID params
func (o *GetUsersUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users UID params
func (o *GetUsersUIDParams) WithContext(ctx context.Context) *GetUsersUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users UID params
func (o *GetUsersUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users UID params
func (o *GetUsersUIDParams) WithHTTPClient(client *http.Client) *GetUsersUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users UID params
func (o *GetUsersUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the get users UID params
func (o *GetUsersUIDParams) WithUID(uid string) *GetUsersUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the get users UID params
func (o *GetUsersUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
