// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// GetUsersUIDPermissionsReader is a Reader for the GetUsersUIDPermissions structure.
type GetUsersUIDPermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersUIDPermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersUIDPermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersUIDPermissionsOK creates a GetUsersUIDPermissionsOK with default headers values
func NewGetUsersUIDPermissionsOK() *GetUsersUIDPermissionsOK {
	return &GetUsersUIDPermissionsOK{}
}

/*GetUsersUIDPermissionsOK handles this case with default header values.

Success.
*/
type GetUsersUIDPermissionsOK struct {
	Payload *models.UserPermissions
}

func (o *GetUsersUIDPermissionsOK) Error() string {
	return fmt.Sprintf("[GET /users/{uid}/permissions][%d] getUsersUidPermissionsOK  %+v", 200, o.Payload)
}

func (o *GetUsersUIDPermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserPermissions)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
