// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dcos/client-go/dcos/iam/models"
)

// NewPatchUsersUIDParams creates a new PatchUsersUIDParams object
// with the default values initialized.
func NewPatchUsersUIDParams() *PatchUsersUIDParams {
	var ()
	return &PatchUsersUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchUsersUIDParamsWithTimeout creates a new PatchUsersUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchUsersUIDParamsWithTimeout(timeout time.Duration) *PatchUsersUIDParams {
	var ()
	return &PatchUsersUIDParams{

		timeout: timeout,
	}
}

// NewPatchUsersUIDParamsWithContext creates a new PatchUsersUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchUsersUIDParamsWithContext(ctx context.Context) *PatchUsersUIDParams {
	var ()
	return &PatchUsersUIDParams{

		Context: ctx,
	}
}

// NewPatchUsersUIDParamsWithHTTPClient creates a new PatchUsersUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchUsersUIDParamsWithHTTPClient(client *http.Client) *PatchUsersUIDParams {
	var ()
	return &PatchUsersUIDParams{
		HTTPClient: client,
	}
}

/*PatchUsersUIDParams contains all the parameters to send to the API endpoint
for the patch users UID operation typically these are written to a http.Request
*/
type PatchUsersUIDParams struct {

	/*UserUpdateObject
	  Password/description.

	*/
	UserUpdateObject *models.UserUpdate
	/*UID
	  The ID of the user account to modify.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch users UID params
func (o *PatchUsersUIDParams) WithTimeout(timeout time.Duration) *PatchUsersUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch users UID params
func (o *PatchUsersUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch users UID params
func (o *PatchUsersUIDParams) WithContext(ctx context.Context) *PatchUsersUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch users UID params
func (o *PatchUsersUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch users UID params
func (o *PatchUsersUIDParams) WithHTTPClient(client *http.Client) *PatchUsersUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch users UID params
func (o *PatchUsersUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserUpdateObject adds the userUpdateObject to the patch users UID params
func (o *PatchUsersUIDParams) WithUserUpdateObject(userUpdateObject *models.UserUpdate) *PatchUsersUIDParams {
	o.SetUserUpdateObject(userUpdateObject)
	return o
}

// SetUserUpdateObject adds the userUpdateObject to the patch users UID params
func (o *PatchUsersUIDParams) SetUserUpdateObject(userUpdateObject *models.UserUpdate) {
	o.UserUpdateObject = userUpdateObject
}

// WithUID adds the uid to the patch users UID params
func (o *PatchUsersUIDParams) WithUID(uid string) *PatchUsersUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the patch users UID params
func (o *PatchUsersUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchUsersUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserUpdateObject != nil {
		if err := r.SetBodyParam(o.UserUpdateObject); err != nil {
			return err
		}
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
