/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type PhaseStep struct {
	Id      string `json:"id,omitempty"`
	Status  string `json:"status,omitempty"`
	Name    string `json:"name,omitempty"`
	Message string `json:"message,omitempty"`
}
