/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type Marathon struct {
	V2AppMustacheTemplate string `json:"v2AppMustacheTemplate"`
}
