/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SystemHealth struct {
	MesosID                string       `json:"mesosID,omitempty"`
	Ip                     string       `json:"ip,omitempty"`
	Hostname               string       `json:"hostname,omitempty"`
	NodeRole               string       `json:"nodeRole,omitempty"`
	DcosVersion            string       `json:"dcosVersion,omitempty"`
	DcosDiagnosticsVersion string       `json:"dcosDiagnosticsVersion,omitempty"`
	Units                  []UnitHealth `json:"units,omitempty"`
}
