/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type KubernetesAuthDataResponse struct {
	CaCrt string `json:"caCrt"`
	Token string `json:"token"`
}
