/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type PlanPhase struct {
	Name     string      `json:"name,omitempty"`
	Id       string      `json:"id,omitempty"`
	Strategy string      `json:"strategy,omitempty"`
	Status   string      `json:"status,omitempty"`
	Steps    []PhaseStep `json:"steps,omitempty"`
}
