/*
 * Cosmos
 *
 * DC/OS Package and Service
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type UnitHealth struct {
	Id          string `json:"id,omitempty"`
	Name        string `json:"name,omitempty"`
	Health      int32  `json:"health,omitempty"`
	Output      string `json:"output,omitempty"`
	Description string `json:"description,omitempty"`
	Help        string `json:"help,omitempty"`
}
